name: axentro 
description: Axentro flutter crypto package
version: 0.0.1
author: Kingsley Hendrickse <kingsley@axentro.io>
homepage: https://axentro.io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0  
  pointycastle: ^3.0.1
  ed25519_edwards: ^0.1.0 
  ed25519_hd_key: ^2.0.0
  bip39: ^1.0.6
  quiver: ^3.0.0
  convert: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
